INGAME_POINTS = frozenset([
    "Będzin",
    "Będzin Ksawera",
    "Będzin Miasto",
    "Biała Rawska",
    "Brwinów",
    "Bukowno",
    "Bukowno Przymiarki",
    "Charsznica",
    "Chruszczobród",
    "Chrząstowice Olkuskie",
    "Dąbr.Gór.Strzem. R75",
    "Dąbrowa Górn. Ząbkowice DZA R.4/7",
    "Dąbrowa Górnicza",
    "Dąbrowa Górnicza Gołonóg",
    "Dąbrowa Górnicza Huta Katowice",
    "Dąbrowa Górnicza Huta Katowice R7",
    "Dąbrowa Górnicza Pogoria",
    "Dąbrowa Górnicza Południowa",
    "Dąbrowa Górnicza Sikorka",
    "Dąbrowa Górnicza Strzemieszyce",
    "Dąbrowa Górnicza Towarowa DTA R5",
    "Dąbrowa Górnicza Wschodnia",
    "Dąbrowa Górnicza Ząbkowice",
    "Dąbrowa Górnicza Ząbkowice DZA",
    "Dąbrowa Górnicza Ząbkowice GTB",
    "Dorota",
    "Gajówka",
    "Gajówka APO",
    "Gniewiecin",
    "Góra Włodowska",
    "Grodzisk Maz. R58",
    "Grodzisk Mazowiecki",
    "Grodzisk Mazowiecki R64",
    "Idzikowice",
    "Idzikowice Roz.12",
    "Idzikowice Roz.18",
    "Jaktorów",
    "Jaroszowiec Olkuski",
    "Jeżówka",
    "Józefinów",
    "Józefinów Roz.2",
    "Juliusz",
    "Katowice",
    "Katowice Janów",
    "Katowice M. Kmb R234",
    "Katowice M. Roz. 233",
    "Katowice Much. KMB",
    "KATOWICE MUCHOWIEC STASZIC",
    "Katowice Szopienice Południowe",
    "Katowice Zawodzie",
    "Klimontów",
    "Knapówka",
    "Knapówka R2",
    "Korytów",
    "Kozioł",
    "Kozioł R12",
    "Kozłów",
    "Łazy",
    "Łazy Grupa Węglarkowa ŁGW",
    "Łazy Ła",
    "Łazy Łc",
    "Łazy R52",
    "Milanówek",
    "Olkusz",
    "Olszamowice",
    "Opoczno Południe",
    "Parzniew",
    "Piastów",
    "Pilichowice",
    "Pruszków",
    "Przemiarki",
    "Psary",
    "Psary Roz.40",
    "Sędziszów",
    "Sławków",
    "Sosnowiec Dańdówka",
    "Sosnowiec Gł. pzs R52",
    "Sosnowiec Główny",
    "Sosnowiec Kazimierz",
    "Sosnowiec Kazimierz PZS SKZ1",
    "Sosnowiec Kazimierz PZS SKZ2",
    "Sosnowiec Południowy",
    "Sosnowiec Porąbka",
    "Sprowa",
    "Starzyny",
    "Starzyny R5",
    "Staszic",
    "Stawiska",
    "Strzałki",
    "Szeligi",
    "Tunel",
    "Tunel R13",
    "Warszawa Centralna",
    "Warszawa Ursus",
    "Warszawa Ursus Niedźwiadek",
    "Warszawa Włochy",
    "Warszawa Wschodnia",
    "Warszawa Zach. R10",
    "Warszawa Zach. R19",
    "Warszawa Zachodnia",
    "Wiesiółka",
    "Włoszczowa Północ",
    "Wolbrom",
    "Zarzecze",
    "Zarzecze APO",
    "Zawiercie",
    "Zawiercie Borowe Pole",
    "Zawiercie GT",
])

TRAIN_TYPES = {
    "E186 (Traxx)": "E186",
    "E6ACTa (Dragon2)": "E6ACTa",
    "E6ACTadb (Dragon2)": "E6ACTadb",
    "ED250 (Pendolino)": "ED250",
    "EN57 (5B+6B+5B)": "EN57",
    "EN71 (5B+6B+6B+5B)": "EN71",
    "EN76 (22WE)": "EN76",
    "EN96 (34WE)": "EN96",
    "EP07 (4E)": "EP07",
    "EP08 (102E)": "EP08",
    "ET22 (201E)": "ET22",
    "ET25 (Dragon2)": "ET25",
    "EU07 (4E)": "EU07",
}

CONTROLLABLE_POINTS = {
    "Będzin": "B",
    "Biała Rawska": "BR",
    "Bukowno": "Bo",
    "Dąbrowa Górnicza": "DG",
    "Dąbrowa Górnicza Huta Katowice": "DGHK",
    "Dąbrowa Górnicza Wschodnia": "DW",
    "Dąbrowa Górnicza Ząbkowice": "DZ",
    "Dorota": "Dra",
    "Góra Włodowska": "GW",
    "Grodzisk Mazowiecki": "Gr",
    "Idzikowice": "Id",
    "Juliusz": "Ju",
    "Katowice": "KO",
    "Katowice Zawodzie": "KZ",
    "Knapówka": "Kn",
    "Korytów": "Kr",
    "Kozłów": "Kz",
    "Łazy": "LB",
    "Łazy Ła": "ŁA",
    "Łazy Łc": "ŁC",
    "Olszamowice": "Ol",
    "Opoczno Południe": "Op",
    "Pilichowice": "Pi",
    "Pruszków": "Pr",
    "Psary": "Ps",
    "Sławków": "Sl",
    "Sosnowiec Gł. pzs R52": "SG5",
    "Sosnowiec Główny": "SG",
    "Sosnowiec Kazimierz": "SKz",
    "Sosnowiec Południowy": "Spł1",
    "Strzałki": "St",
    "Szeligi": "Se",
    "Tunel": "Tl",
    "Włoszczowa Północ": "WP",
    "Zawiercie": "Zw",
}
